sudo: true

install:
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/master/scripts/start_docker.sh)
  - docker pull clapclapexcitement/docker-clouder
  - docker run clapclapexcitement/docker-clouder

script:
  - echo "hello"
